import { createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { chromium, type Page } from 'playwright';
import { TelegramNotifier } from './telegram/TelegramNotifier.js';
import type { CollectedAd } from './domain/ad.js';

const SCANNER_API='https://qfpwpqflqiwjqpojmngy.supabase.co/functions/v1/scanner-api';
const LIBRARY='https://adstransparency.google.com/?region=anywhere';
type Target={id:string;name:string;query:string;channel:string;source_url:string;is_active:boolean};
type Workspace={id:string;chat_id:number;project_name:string;geo:string;competitors:Target[]};
type ParsedAd={libraryId:string;advertiser:string;startedAt?:string;format:'IMAGE'|'VIDEO'|'UNKNOWN';cta?:string;destinationType:string;primaryText:string;landingUrl?:string;creativeUrl?:string;adLibraryUrl:string};
const token=()=>{const t=process.env.TELEGRAM_BOT_TOKEN;if(!t)throw new Error('TELEGRAM_BOT_TOKEN is required');return t;};
const headers=()=>({authorization:`Bearer ${token()}`,'content-type':'application/json'});
async function workspaces():Promise<Workspace[]>{const r=await fetch(`${SCANNER_API}?channel=GOOGLE`,{headers:headers()});if(!r.ok)throw new Error(`scanner-api GET ${r.status}: ${await r.text()}`);return ((await r.json()) as any).workspaces||[];}
async function reconcile(ws:string,c:string,ads:ParsedAd[]){const r=await fetch(SCANNER_API,{method:'POST',headers:headers(),body:JSON.stringify({action:'reconcile',workspaceId:ws,competitorId:c,ads})});if(!r.ok)throw new Error(`reconcile ${r.status}: ${await r.text()}`);return r.json() as Promise<{events:any[]}>;}
const hash=(s:string)=>createHash('sha256').update(s).digest('hex').slice(0,24);
const clean=(s:string)=>s.replace(/\s+/g,' ').trim();
function normalizeDomain(v:string){return v.toLowerCase().replace(/^https?:\/\//,'').replace(/^www\./,'').split('/')[0].split(':')[0];}
async function searchDomain(page:Page,domain:string){await page.goto(LIBRARY,{waitUntil:'domcontentloaded',timeout:60000});await page.waitForTimeout(3000);const inputs=page.locator('input');let input=null as any;for(let i=0;i<await inputs.count();i++){const el=inputs.nth(i);if(await el.isVisible().catch(()=>false)){input=el;break;}}if(!input)throw new Error('Google Transparency search input not found');await input.fill(domain);await page.waitForTimeout(1800);const exact=page.getByText(domain,{exact:false}).first();if(await exact.isVisible().catch(()=>false))await exact.click({timeout:3000}).catch(()=>{});else await input.press('Enter');await page.waitForTimeout(6000);for(let i=0;i<6;i++){await page.mouse.wheel(0,1800);await page.waitForTimeout(800);}}
async function extract(page:Page,domain:string):Promise<{ads:ParsedAd[];explicitEmpty:boolean;verified:boolean}>{const body=clean(await page.locator('body').innerText().catch(()=>''));const verified=body.toLowerCase().includes(domain.toLowerCase());const explicitEmpty=/no ads|no results|couldn't find|did not find/i.test(body);const raw=await page.evaluate(()=>{const anchors=Array.from(document.querySelectorAll<HTMLAnchorElement>('a[href]')).filter(a=>/\/advertiser\/|\/creative\//i.test(a.href));const out:any[]=[];const seen=new Set<string>();for(const a of anchors){let n:HTMLElement|null=a;let card:HTMLElement|null=null;for(let d=0;d<10&&n;d++){const t=(n.innerText||'').trim();if(t.length>=40&&t.length<=6000)card=n;n=n.parentElement;}if(!card)continue;const href=a.href;const key=href+'|'+card.innerText.slice(0,300);if(seen.has(key))continue;seen.add(key);const links=Array.from(card.querySelectorAll<HTMLAnchorElement>('a[href]')).map(x=>x.href);const imgs=Array.from(card.querySelectorAll<HTMLImageElement>('img')).map(x=>({url:x.currentSrc||x.src,w:x.naturalWidth,h:x.naturalHeight})).filter(x=>x.url);const vids=Array.from(card.querySelectorAll<HTMLVideoElement>('video')).flatMap(v=>[v.currentSrc,v.src,...Array.from(v.querySelectorAll<HTMLSourceElement>('source[src]')).map(s=>s.src)]).filter(Boolean);out.push({href,text:card.innerText,links,imgs,vids});}return out;});
 const ads:ParsedAd[]=[];const seen=new Set<string>();for(const r of raw as any[]){const text=clean(r.text||'');const external=r.href.match(/\/creative\/([^/?#]+)/i)?.[1]||`G-${hash(r.href+'|'+text)}`;if(seen.has(external))continue;seen.add(external);const landing=(r.links as string[]).find((x:string)=>{try{const u=new URL(x);return !u.hostname.endsWith('google.com')&&!u.hostname.includes('adstransparency.google');}catch{return false;}});const video=(r.vids as string[]).find((x:string)=>/^https?:/i.test(x));const image=(r.imgs as any[]).filter(x=>/^https?:/i.test(x.url)&&x.w>200&&x.h>120).sort((a,b)=>b.w*b.h-a.w*a.h)[0]?.url;const advertiser=text.split(/\n/).map(clean).filter(Boolean)[0]||domain;const started=text.match(/(?:First shown|Started|Published)[:\s]+([^|·]+)/i)?.[1]?.trim();ads.push({libraryId:external,advertiser,startedAt:started,format:video?'VIDEO':image?'IMAGE':'UNKNOWN',destinationType:landing?'WEBSITE':'GOOGLE_INTERNAL',primaryText:text.slice(0,5000),landingUrl:landing,creativeUrl:video||image,adLibraryUrl:page.url()});}return {ads,explicitEmpty,verified};}
function collected(ad:any):CollectedAd{return {source:'GOOGLE',externalId:ad.libraryId,fingerprint:`GOOGLE:${ad.libraryId}`,format:ad.format||'UNKNOWN',primaryText:ad.primaryText||'',cta:ad.cta,landingUrl:ad.landingUrl,creativeUrl:ad.creativeUrl,adLibraryUrl:ad.adLibraryUrl,raw:{advertiser:ad.advertiser,startedAt:ad.startedAt,destinationType:ad.destinationType}};}
async function main(){await mkdir('artifacts/google-production',{recursive:true});const notifier=new TelegramNotifier();const browser=await chromium.launch({headless:false,args:['--no-sandbox','--disable-blink-features=AutomationControlled']});const context=await browser.newContext({viewport:{width:1600,height:1200},locale:'en-US',userAgent:'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36'});try{for(const ws of await workspaces()){for(const c of ws.competitors.filter(x=>x.channel==='GOOGLE'&&x.is_active)){const domain=normalizeDomain(c.query||c.source_url);const page=await context.newPage();try{console.log(`[google] ${ws.project_name} domain=${domain}`);await searchDomain(page,domain);const result=await extract(page,domain);await writeFile(`artifacts/google-production/${ws.id}-${c.id}.json`,JSON.stringify(result,null,2));if(!result.verified&&!result.explicitEmpty){console.log(`[google] ${domain} INCOMPLETE — exact domain not verified`);continue;}if(result.ads.length===0&&!result.explicitEmpty){console.log(`[google] ${domain} INCOMPLETE — no ad cards`);continue;}const {events}=await reconcile(ws.id,c.id,result.ads);console.log(`[google] ${domain} ads=${result.ads.length} events=${events.length}`);for(const e of events){if(e.type==='STOPPED')await notifier.sendStopped({chatId:ws.chat_id,projectName:ws.project_name,competitorName:c.name,adId:String(e.ad.libraryId||''),source:'GOOGLE',startedAt:e.ad.startedAt,lastSeenAt:e.ad.lastSeenAt});else await notifier.sendNewAd({chatId:ws.chat_id,projectName:ws.project_name,geo:ws.geo,competitorName:c.name,eventType:e.type,ad:collected(e.ad)});}}finally{await page.screenshot({path:`artifacts/google-production/${ws.id}-${c.id}.png`,fullPage:true}).catch(()=>{});await page.close();}}}}finally{await browser.close();}}
main().catch(e=>{console.error(e);process.exit(1);});
